// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artcile is the predicate function for artcile builders.
type Artcile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
